version: "3.8"

services:
  database:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./database:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb:latest
    depends_on: [ database ]
    env_file:
      - .env
    ports:
      - '8081:8081'

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: on-failure
#    ports:
#      - '8080:8080'
#    depends_on: [ database ]

volumes:
  database: